### ISSUE TITLE
Not currently buildable

### ISSUE THREAD

**Issue by Vectrobe** [GPUOpen-LibrariesAndSDKs/TAN#3]
Simply open with a fresh install of VS 2019 and attempt to build; several issues will present themselves, scattered across the projects;
- $(OCL_Include) is never defined, and in fact outright missing on some critical projects
- vscwprintf doesn't exist
- _Longlong doesn't exist, it's not even a sound type name
- CL_MEM_USE_PERSISTENT_MEM_AMD doesnt exist, it's not part of the standard CL library

among with several bad cast warnings that would definitely result in undefined behaviour, such as size_t (ui64) to cl_uint (ui32), and some unreferenced variables that exist for no reason...

**Comment by mirh** [comment]
> CL_MEM_USE_PERSISTENT_MEM_AMD doesnt exist, it's not part of the standard CL library

It's part of AMD's sdk. 
You can go with the [original one](https://archive.org/download/AMDAPPSDK), or try the [new light version](https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases).

**Comment by Vectrobe** [comment]
- The SDK is not supported, and last I checked doesn't install or build correctly anymore
- Already tried OCL-SDK, it's outdated and doesn't work properly either, or at least not without directory tomfoolery

**Comment by GeoffPark** [comment]
The public version of TAN was released over a year ago, and does not support VS 2019.  After installing OCL-SDK Light [ https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases ] TAN should build using VS 2015 or 2013.  

The next release will support VS 2019, and include a faster non-uniform partitioned convolution algorithm, and improved CPU support.  Linux support is also planned.

**Comment by Vectrobe** [comment]
Might want to keep it open until said release then, as VS 2015 and 2013 are unsupported, by a long shot...

**Comment by Vectrobe** [comment]
This should have been 2017 compliant anyway
